kind: Service
apiVersion: v1
metadata:
  name: survey-generator-service
spec:
  type: NodePort
  selector:
    app: survey-generator-app
  ports:
  - protocol: TCP
    port:  3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-generator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: survey-generator-app
  template:
    metadata:
      labels:
        app: survey-generator-app
    spec:
      containers:
        - name: survey-generator-app
          image: "ecerqueira/survey-generator:1.0"
          imagePullPolicy: Always
          ports: 
            - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: survey-generator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /hello
        backend:
          serviceName: survey-generator-service
          servicePort: 3000