{{- if .Values.ingress.enabled -}}
{{- $fullName := include "survey-generator-app.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $servicePort := .Values.ingress.servicePort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ include "survey-generator-app.name" . }}
    chart: {{ include "survey-generator-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - path: {{ $ingressPath }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $servicePort }}
{{- end }}