# Default values for survey-generator-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: ecerqueira/survey-generator
  tag: "1.0"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3000

ingress:
  enabled: true
  path: /
  servicePort: 3000
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - survey-generator-app